apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: your-app-name
  namespace: default
  labels:
    team: awesome-team
spec:
  image: FROM-CI
  port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: "/status"
    port: 8080
  replicas:
    min: 1
    max: 2
