version: 2.1
orbs:
  nais: 'navikt/nais-deployment:XYZ'
workflow:
  deploy-docker-and-nais:
    jobs:
      - nais/deploy:
          context: NAIS deployment
          repo: navikt/example-repo
          image: navikt/example-image
          github-app-id: 1337
          nais-template: nais.yaml
          environment: dev-fss
